name: generate page site
on:
  push:
    branches:  [master]
  pull_request:
    branches:  [master]

permissions:
  checks: write
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Publish to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - run: npm ci
      - run: npm run docs:build
      - name: Create Tag
        uses: jaywcjlove/create-tag-action@v1.3.20
        if: ${{ github.ref == 'refs/heads/master' }}
        id: create_tag
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        uses: jaywcjlove/create-tag-action@v1.3.20
        if: steps.create_tag.outputs.successful
        id: tag_release
        with:
          release: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        if: steps.tag_release.outputs.successful
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId:  ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: dockit-site
          directory: dist
          # Optional: Enable this if you want to have GitHub Deployments triggered
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          environment: production
